export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/users";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/Certifications";
export * from "@/pages/dashboard/Evenements";
export * from "@/pages/dashboard/Overview";
export * from "@/pages/dashboard/AISalhiDashboard";
export * from "@/pages/dashboard/video-analyzer";
export * from "@/pages/dashboard/restaurants";
export * from "@/pages/dashboard/produits";
export * from "@/pages/dashboard/reservations";
export * from "@/pages/dashboard/activities-admin";
export * from "@/pages/dashboard/zones-admin";
export * from "@/pages/dashboard/Energies";
export { default as EmpreinteCarbone } from "@/pages/dashboard/EmpreinteCarbone";
