from .user import User
from .touriste import Touriste
from .guide import Guide
from .destination import Destination
from .ville import Ville
from .region import Region
from .hebergement import Hebergement
from .hotel import Hotel
from .maison_hote import MaisonHote
from .activite import Activite
from .randonnee import Randonnee
from .transport import Transport
from .eco_transport import EcoTransport
from .transport_non_motorise import TransportNonMotorise
from .restaurant import Restaurant
from .restaurant_eco import RestaurantEco
from .produit_local import ProduitLocal
from .produit_local_bio import ProduitLocalBio
from .certification_eco import CertificationEco
from .empreinte_carbone import EmpreinteCarbone
from .energie_renouvelable import EnergieRenouvelable
from .zone_naturelle import ZoneNaturelle
from .evenement import Evenement
from .festival import Festival
from .foire import Foire

